### ISSUE TITLE
Correct Domain Label Risk Management...to Risk Communication

### ISSUE THREAD

**Issue by pippin1** [CommunityHealthAcademy/django-covid#44]
the attached domain screenshot is reading as: Risk Management and Community Engagement it should read:

Risk Communication and Community Engagement (RCCE)

It will need to be changed in these places:

- change domain name on home page
- change checkbox under add a resource
- change menu under browse resources
- the title of the help page that appears when the domain name is selected on the landing page

(hope that is everything)

If you are interested the domain name is based on the following WHO Guidance: https://www.who.int/publications-detail/risk-communication-and-community-engagement-(rcce)-action-plan-guidance 

<img width="293" alt="Screen Shot 2020-05-20 at 11 42 08 AM" src="https://user-images.githubusercontent.com/65673040/82471200-5fb8b800-9a94-11ea-9b68-ca2b69a0decb.png">

**Comment by alexlittle** [comment]
This is updated now, although the icon doesn't appear.... this is because there is a reference to the domain 'slug' in the UI code, so once the ui is updated, this can be fixed
