### ISSUE TITLE
Resource uploaded but unavailable for download

### ISSUE THREAD

**Issue by pippin1** [CommunityHealthAcademy/django-covid#48]
The attached image reflects the failure to see the PACK Algorithm job aid (a powerpoint file) available for download although is was successfully uploaded and applied for both IPC and Case Management (as far as I know this is the  only  resource where this has occurred)

<img width="1351" alt="Screen Shot 2020-05-22 at 3 57 29 PM" src="https://user-images.githubusercontent.com/65673040/82705313-75211400-9c45-11ea-98bf-02d00a117805.png">

**Comment by alexlittle** [comment]
In the database, there aren;t any files or urls associated with this resource.... so looks like the file wasn't actually uploaded for this.
